NewsWebApp/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewsWebApp.Models;

namespace NewsWebApp.Controllers
{
    public class NewsController : Controller
    {
        private readonly NewsContext _context;

        public NewsController(NewsContext context)
        {
            _context = context;
        }

        // GET: News
        public async Task<IActionResult> Index()
        {
            return View(await _context.Newsdetails.ToListAsync());
        }
        // GET: News/Create
        
        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Create(Newsdetail news, List<IFormFile> PhotoForPreview, List<IFormFile> PhotoForFulltext)
        {
            if (ModelState.IsValid)
            {
                Newsdetail ns = await _context.Newsdetails
                    .FirstOrDefaultAsync(u => u.Name == news.Name && u.Summary == news.Summary && u.PhotoForFulltext == news.PhotoForFulltext);
                if (ns == null)
                {
                     ModelState.AddModelError("Name", "Заполняйте все поля правильно!");
                    ModelState.AddModelError("Date", "Дата не устоновлен!");
                }
                else
                {
                    foreach (var item in PhotoForPreview)
                    {
                        if (item.Length > 0)
                        {
                            using (var stream = new MemoryStream())
                            {
                                await item.CopyToAsync(stream);
                                news.PhotoForPreview = stream.ToArray();
                            }
                        }

                    }
                    foreach (var item in PhotoForFulltext)
                    {
                        if (item.Length > 0)
                        {
                            using (var stream = new MemoryStream())
                            {
                                await item.CopyToAsync(stream);
                                news.PhotoForFulltext = stream.ToArray();
                            }
                        }
                    }
                    _context.Newsdetails.Add(news);
                    _context.SaveChanges();
                    ModelState.Clear();
                }
            }
           
            return View();
        }

        // GET: News/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsdetail = await _context.Newsdetails.FindAsync(id);
            if (newsdetail == null)
            {
                return NotFound();
            }
            return View(newsdetail);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, List<IFormFile> PhotoForPreview, List<IFormFile> PhotoForFulltext, [Bind("ID,Name,Language,Category,Date,Summary,FullContent")] Newsdetail newsdetail)
        {
            if (id != newsdetail.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                
                if (PhotoForPreview == null)
                {
                    ModelState.AddModelError("ModelOnly", "Заполняйте все поля правильно!");
                    
                }
                else
                {
                    foreach (var item in PhotoForPreview)
                    {
                        if (item.Length > 0)
                        {
                            using (var stream = new MemoryStream())
                            {
                                await item.CopyToAsync(stream);
                                newsdetail.PhotoForPreview = stream.ToArray();
                            }
                        }

                    }
                    foreach (var item in PhotoForFulltext)
                    {
                        if (item.Length > 0)
                        {
                            using (var stream = new MemoryStream())
                            {
                                await item.CopyToAsync(stream);
                                newsdetail.PhotoForFulltext = stream.ToArray();
                            }
                        }
                    }
                    _context.Update(newsdetail);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(newsdetail);
        }

        // GET: News/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var newsdetail = await _context.Newsdetails
                .FirstOrDefaultAsync(m => m.ID == id);
            if (newsdetail == null)
            {
                return NotFound();
            }

            return View(newsdetail);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var newsdetail = await _context.Newsdetails.FindAsync(id);
            _context.Newsdetails.Remove(newsdetail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NewsdetailExists(int id)
        {
            return _context.Newsdetails.Any(e => e.ID == id);
        }
    }
}

NewsWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</head>
<body style="background: #01294a ">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" >
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="navbar-brand" href="~/Home/Index">Логотип</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Home/Policy">Политика</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Home/Buisiness">Бизнес</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Home/ShowBuisiness">Шоубизнес</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/Home/Soc">Общество</a>
                </li>
            </ul>
        </div>
        <div class="mx-auto order-0">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a style="text-decoration: none; width:100px;  display:block; " asp-controller="News" asp-action="Create">Добавить</a>
                    </li>

                    <li class="nav-item">
                        <a style="text-decoration: none;" asp-controller="Account" asp-action="Logout">Выйти</a>
                    </li>
                }
                else
                {
                    <li class="btn">
                        <a style="text-decoration: none;" asp-controller="Account" asp-action="Login">Войти</a>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <br><br>
    <!--основной контент-->
    <div class="container">
        @RenderBody()

    </div>
    <hr />
    <footer style="background: #f8f9fa" class="page-footer font-small blue pt-4">
        <div class="container-fluid text-center text-md-left">
            <div class="row">
                <div class="col-md-6 mt-md-0 mt-3">
                    <h5 class="text-uppercase">СОДЕРЖАНИЕ ФУТЕРA</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                </div>
                <hr class="clearfix w-100 d-md-none pb-3">
                <div class="col-md-3 mb-md-0 mb-3">
                    <h5 class="text-uppercase">Links</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#!">Link 1</a>
                        </li>
                        <li>
                            <a href="#!">Link 2</a>
                        </li>
                        <li>
                            <a href="#!">Link 3</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-3 mb-md-0 mb-3">
                    <h5 class="text-uppercase">Links</h5>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#!">Link 1</a>
                        </li>
                        <li>
                            <a href="#!">Link 2</a>
                        </li>
                        <li>
                            <a href="#!">Link 3</a>
                        </li>
                    </ul>

                </div>
            </div>
        </div>
        <div class="footer-copyright text-center py-3">
            © 2019 Copyright:
            <a href="#!"> Nurzhigit Algauly</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"           
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)

</body>
</html>